### ISSUE TITLE
Mentor OnBoarding Flow

### ISSUE THREAD

**Issue by ashishapy** [heliumink/vitaink#8]
Listing issues / TODO in mentor on-boarding flow.
- [ ] Update History is getting update, every time  on click of submit button.

** In Application detail: **
- [ ] Country drop down is coming up with list of countries.
- [ ] Implement user friendly field validation error message.
- [ ] Check if 'Resume' is uploaded and accessible.
- [ ] Implement url validation.

** Project Details: **
- [ ] 'Project cover' is uploaded and accessible.
- [ ] Implement notification to admin / screener on click of Submit button.

** Screening: **
- [ ] 'Project Review Comments' to be editable by screener only.

** Roadmap: **
- [ ] Change datepicker for 'Date for the milestone'.
- [ ] Implement notification to admin / screener on click of Submit button.
